// Auto-generated by script
using UnrealBuildTool;

public class LudusWebUi : ModuleRules
{
    public LudusWebUi(ReadOnlyTargetRules Target)
        : base(Target)
    {
		bUsePrecompiled = true;
		PrecompileForTargets = PrecompileTargetsType.Any;
        PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;
        PublicDependencyModuleNames.AddRange(
            new string[]
            {
                "Core",
                "CoreUObject",
                "Engine",
                "InputCore",
                "Slate",
                "SlateCore",
                "UMG",
                "LudusClient",
                "Projects",
                "UnrealEd",
                "LudusMarkdown",
                "Documentation",
                "GraphEditor",
                "BlueprintGraph",
                "MessageLog",
                "ApplicationCore",
                "Json",
            }
        );
        PrivateDependencyModuleNames.AddRange(
            new string[] { "LudusCore", "LudusClient", "WebBrowser" }
        );
    }
}
