import { FormEvent, useCallback, useEffect, useState } from "react";
import "./App.css";

interface UE {
  bridge?: {
    // mind that this must stay lowever case
    // because this is how it is generated by Unreal
    sendtoeditor: (message: string) => void;
  };
}

interface Window {
  ue?: UE;
  sendToWeb?: (message: string) => void;
}

function App() {
  const [received, setReceived] = useState<string[]>([]);

  useEffect(() => {
    const w = window as Window;

    w.sendToWeb = function (message: string) {
      setReceived((prev) => [...prev, message]);
    };

    return () => {
      // Clean up the global function when component unmounts
      delete w.sendToWeb;
    };
  }, []);

  const onSend = useCallback((e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    const formObject: Record<string, string> = {};
    formData.forEach((value, key) => {
      formObject[key] = value.toString();
    });
    const jsonString = JSON.stringify(formObject);
    const bridge = (window as Window).ue?.bridge;
    if (bridge) {
      bridge.sendtoeditor(jsonString);
      // Reset form after successful send
      e.currentTarget.reset();
    } else {
      console.error("Bridge to Unreal Engine not available");
      // Add UI feedback for the user that message sending failed
    }
  }, []);

  return (
    <div className="App">
      <header className="App-header">
        <form onSubmit={onSend}>
          <div>
            <h4>Message to Unreal</h4>
            <div>
              <label htmlFor="title">Title</label>
              <input
                id="title"
                name="title"
                type="text"
                placeholder="Enter title here"
              />
            </div>
            <div>
              <label htmlFor="description">Description</label>
              <input
                id="description"
                name="description"
                type="text"
                placeholder="Enter description here"
              />
            </div>
            <div>
              <label htmlFor="priority">Priority</label>
              <select
                id="priority"
                name="priority"
              >
                <option value="low">Low</option>
                <option value="medium">Medium</option>
                <option value="high">High</option>
              </select>
            </div>
          </div>
          <button type="submit">Send to Unreal</button>
        </form>
        <div>
          <h4>Received from Unreal:</h4>
          <ul>
            {received.map((message, index) => (
              <li key={`message-${index}`}>{message}</li>
            ))}
          </ul>
        </div>
      </header>
    </div>
  );
}

export default App;
